sp = float(67.83643)
rj = float(36.67866)
mg = float(29.22988)
es = float(27.16548)
outros = float(19.84953)
total = float(sp + rj + mg + es + outros)
print("Faturamento total mensal:", total)
percent_sp = ((sp/total)*100)
percent_rj = ((rj/total)*100)
percent_mg = ((mg/total)*100)
percent_es = ((es/total)*100)
percent_outros = ((outros/total)*100)

print("Porcentagem de São Paulo: ", percent_sp)
print("Porcentagem do Rio de Janeiro: ", percent_rj)
print("Porcentagem de Minas Gerais: ", percent_mg)
print("Porcentagem de Espirito Santo: ", percent_es)
print("Porcentagem de Outros: ", percent_outros)